version: '3.8'

services:
  apache2:
    container_name: apache2
    build:
      context: ./apache2
      args:
        DB_SRV_ADDR: postgresql
        ZBX_SRV_ADDR: zabbix-server
    ports:
      - "8080:80"
    networks:
      - zabbix-stack
  postgresql:
    container_name: postgresql
    build: 
      context: ./postgresql
    networks:
      - zabbix-stack
  zabbix-server:
    container_name: zabbix-server
    build:
      context: ./zabbix-server
      args:
        DB_SRV_ADDR: postgresql
    networks:
      - zabbix-stack
networks:
  zabbix-stack:
    ipam:
      config:
        - subnet: 172.20.10.0/24
