version: '3.8'

services:
  apache2:
    container_name: apache2
    build:
      context: ./apache2
      args:
        ZBX_DB_SERVER_ADDR: postgresql
        ZBX_SERVER_ADDR: zabbix-server
        ZBX_MAJOR_VERSION: 5.0
        ZBX_PATCH_VERSION: 5.0.4
    ports:
      - "8080:80"
    networks:
      - zabbix-stack
    volumes:
      - zbx-server-log:/var/log/apache2
    depends_on:
      - postgresql
      - zabbix-server
  postgresql:
    container_name: postgresql
    build:
      context: ./postgresql
      args:
        ZBX_MAJOR_VERSION: 5.0
        ZBX_PATCH_VERSION: 5.0.4
    networks:
      - zabbix-stack
    volumes:
    - zbx-postgres-data:/var/lib/postgresql/10/main
  zabbix-server:
    container_name: zabbix-server
    build:
      context: ./zabbix-server
      args:
        ZBX_DB_SERVER: postgresql
        ZBX_MAJOR_VERSION: 5.0
        ZBX_PATCH_VERSION: 5.0.4
    ports:
      - "10051:10051"
    networks:
      - zabbix-stack
    volumes:
      - zbx-server-log:/opt/zabbix-agent/log
    depends_on:
      - postgresql
  zabbix-agent:
    container_name: zabbix-agent
    build:
      context: ./zabbix-agent
      args:
        ZBX_SERVER: zabbix-server
        ZBX_ACTIVE_SERVER: zabbix-server
        ZBX_AGENT_HOSTNAME: zabbix-server
        ZBX_BUFFER_SEND: 5
        ZBX_BUFFER_SIZE: 200
        ZBX_LISTEN_PORT: 10050
        ZBX_REFRESH_ACTIVE_CHECKS: 60
        ZBX_LOG_FILE_SIZE: 100
        ZBX_START_AGENTS: 5
        ZBX_LISTEN_IP: 0.0.0.0
        ZBX_TIMEOUT: 5
        ZBX_ALLOW_ROOT: 0
        ZBX_UNSAFE_USER_PARAMETERS: 1
        ZBX_LOG_REMOTE_COMMANDS: 0
        ZBX_MAJOR_VERSION: 5.0
        ZBX_PATCH_VERSION: 5.0.4
    ports:
      - "10050:10050"
    networks:
      - zabbix-stack
    privileged: true
    volumes:
      - zbx-agent-log:/opt/zabbix-agent/log
      - /:/rootfs
    depends_on:
      - zabbix-server
networks:
  zabbix-stack:
    ipam:
      config:
        - subnet: 172.20.10.0/24

volumes:
  zbx-agent-log:
  zbx-server-log:
  zbx-postgres-data:

