version: '3.8'

services:
  apache2:
    container_name: apache2
    build:
      context: ./apache2
      args:
        ZBX_DB_SERVER_ADDR: postgresql
        ZBX_SERVER_ADDR: zabbix-server
    ports:
      - "8080:80"
    networks:
      - zabbix-stack
    depends_on:
      - postgresql
      - zabbix-server
  postgresql:
    container_name: postgresql
    build:
      context: ./postgresql
    networks:
      - zabbix-stack
  zabbix-server:
    container_name: zabbix-server
    build:
      context: ./zabbix-server
      args:
        ZBX_DB_SERVER: postgresql
    networks:
      - zabbix-stack
    depends_on:
      - postgresql
networks:
  zabbix-stack:
    ipam:
      config:
        - subnet: 172.20.10.0/24
